name: example
description: "A new Flutter project."
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.8
  storage:
    path: ../../packages/storage

  exception:
    path: ../../packages/exception
  get_it: ^8.0.3
  hive_ce: ^2.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
